Update aqua-sbom.yml

diff --git a/.github/workflows/aqua-sbom.yml b/.github/workflows/aqua-sbom.yml
--- a/.github/workflows/aqua-sbom.yml
+++ b/.github/workflows/aqua-sbom.yml
@@ -1,7 +1,6 @@
-
 name: Build & Test
 
-on: [pull_request,push]
+on: [pull_request, push]
 
 jobs:
   scan:
@@ -16,17 +15,17 @@ jobs:
         with:
           args: trivy fs --sast --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
         env:
-           AQUA_KEY: ${{ secrets.AQUA_KEY }}
-           AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
-           GITHUB_TOKEN: ${{ secrets.TOKEN }}
-           TRIVY_RUN_AS_PLUGIN: 'aqua'
-           ACTIONS_RUNTIME_TOKEN: ${{ secrets.TOKEN }}   
-           TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
-           TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
+          AQUA_KEY: ${{ secrets.AQUA_KEY }}
+          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+          TRIVY_RUN_AS_PLUGIN: 'aqua'
+          ACTIONS_RUNTIME_TOKEN: ${{ secrets.TOKEN }}   
+          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
+          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
           # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)
 
   test:
-    name: Build and Test
+    name: Build, Test, and Generate SBOM
     runs-on: ubuntu-20.04
     needs: scan
     steps:
@@ -36,34 +35,33 @@ jobs:
         with:
           python-version: '3.6'
           cache: 'pip'
+        
       - run: pip install -r requirements.txt
 
       - name: Run DVGA
         run: |
           nohup python3 ./app.py &
+        
       - name: Wait for server (sleep 5 secs)
         run: |
           sleep 5
+        
       - name: Run DVGA Tests
         run: |
           python3 -m pytest tests/*
-  sbom:
-    name: Generate SBOM
-    runs-on: ubuntu-22.04
-    needs: test
-    steps:
-      - uses: actions/checkout@v3
-      # Added for SBOM generation
-      - name: Build Docker Image
+        
+      # SBOM Generation Steps
+      - name: Build Docker Image for SBOM
         run: docker build -t "$GITHUB_REPOSITORY:$GITHUB_RUN_NUMBER" .
-      - name: Manifest Generation
+      
+      - name: Manifest Generation for SBOM
         run: |
           export BILLY_SERVER=https://billy.codesec.aquasec.com
           curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
           if ! cat install.sh.checksum | sha256sum ; then
-          echo "install.sh checksum failed"
-          exit 1
+            echo "install.sh checksum failed"
+            exit 1
           fi
           BINDIR="." sh install.sh
           rm install.sh install.sh.checksum
